// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tquiayawuoqereicsqxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxdWlheWF3dW9xZXJlaWNzcXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjU0NzgsImV4cCI6MjA2MTE0MTQ3OH0.zL6kAiGp9Y-MNQd1D7jnSIt8-oNILtddNbFqblTDhSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);